deployment:
  tasks:
    - export DEPLOYPATH=/home/vjxzcyjr/charlyhb
    - cd $DEPLOYPATH
    - php artisan down || true
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan migrate --force || true
    - php artisan config:cache
    - php artisan route:cache
    - php artisan up || true